# Generated by Django 3.0.5 on 2020-04-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_car', models.CharField(max_length=50, verbose_name='Marca carro')),
                ('modelo_car', models.CharField(choices=[('microauto', 'MICROAUTO'), ('sedan', 'SEDAN'), ('suv', 'SUV'), ('todoterreno', 'TODOTERRENO'), ('coupe', 'COUPE')], default='sedan', max_length=50, verbose_name='Modelo carro')),
                ('color_car', models.CharField(max_length=50, verbose_name='Color carro')),
                ('tipo_car', models.CharField(max_length=50, verbose_name='Tipo de carro')),
                ('patente', models.CharField(max_length=50, unique=True, verbose_name='Patente')),
                ('num_puertas', models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='2', verbose_name='Número de puertas')),
                ('tipo_consumo', models.CharField(choices=[('bencina', 'BENCINA'), ('petrolero', 'PETROLERO')], default='bencina', max_length=10, verbose_name='Tipo de consumo')),
                ('tamaño', models.CharField(choices=[('pequeño', 'PEQUEÑO'), ('mediano', 'MEDIANO'), ('grande', 'GRANDE'), ('extragrande', 'EXTRAGRANDE')], default='mediano', max_length=15, verbose_name='Tamaño carro')),
                ('image_car', models.ImageField(upload_to='products/', verbose_name='Foto del carro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
