# Generated by Django 3.0.5 on 2020-04-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='tipo_car',
        ),
        migrations.AlterField(
            model_name='cars',
            name='num_puertas',
            field=models.IntegerField(default='2', verbose_name='Número de puertas'),
        ),
    ]
