# Generated by Django 3.0.5 on 2020-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre carro')),
                ('marca_car', models.CharField(max_length=50, verbose_name='Marca carro')),
                ('modelo_car', models.CharField(choices=[('microauto', 'MICROAUTO'), ('sedan', 'SEDAN'), ('suv', 'SUV'), ('todoterreno', 'TODOTERRENO'), ('coupe', 'COUPE')], default='sedan', max_length=50, verbose_name='Modelo carro')),
                ('color_car', models.CharField(max_length=50, verbose_name='Color carro')),
                ('patente', models.CharField(max_length=50, unique=True, verbose_name='Patente')),
                ('num_puertas', models.IntegerField(default='2', verbose_name='Número de puertas')),
                ('tipo_consumo', models.CharField(choices=[('bencina', 'BENCINA'), ('petrolero', 'PETROLERO')], default='bencina', max_length=10, verbose_name='Tipo de consumo')),
                ('tamaño', models.CharField(choices=[('pequeño', 'PEQUEÑO'), ('mediano', 'MEDIANO'), ('grande', 'GRANDE'), ('extragrande', 'EXTRAGRANDE')], default='mediano', max_length=15, verbose_name='Tamaño carro')),
                ('image_car', models.ImageField(upload_to='products/', verbose_name='Foto del carro')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
