# Generated by Django 3.0.5 on 2020-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200429_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_car',
            field=models.ImageField(upload_to='cars/', verbose_name='Foto del carro'),
        ),
    ]
